package navaros

import (
	"encoding/json"
)

// RouteDescriptor is a struct that is generated by the router when the public
// variants of the handler binding methods (named after their respective
// http method) are called. The router has a RouteDescriptors method which
// returns these objects, and can be used to build a api map, or pre-filter
// requests before they are passed to the router. This is most useful for
// libraries that wish to extend the functionality of Navaros.
type RouteDescriptor struct {
	Method   HTTPMethod
	Pattern  *Pattern
	Metadata any
}

// MarshalJSON returns the JSON representation of the route descriptor.
func (r *RouteDescriptor) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		Method   HTTPMethod `json:"Method"`
		Pattern  string     `json:"Pattern"`
		Metadata any        `json:"Metadata,omitempty"`
	}{
		Method:   r.Method,
		Pattern:  r.Pattern.String(),
		Metadata: r.Metadata,
	})
}

// UnmarshalJSON parses the JSON representation of the route descriptor.
func (r *RouteDescriptor) UnmarshalJSON(data []byte) error {
	fromJSONStruct := struct {
		Method   HTTPMethod      `json:"Method"`
		Pattern  string          `json:"Pattern"`
		Metadata json.RawMessage `json:"Metadata,omitempty"`
	}{}
	if err := json.Unmarshal(data, &fromJSONStruct); err != nil {
		return err
	}

	pattern, err := NewPattern(fromJSONStruct.Pattern)
	if err != nil {
		return err
	}

	r.Method = fromJSONStruct.Method
	r.Pattern = pattern
	if len(fromJSONStruct.Metadata) > 0 {
		r.Metadata = fromJSONStruct.Metadata
	}

	return nil
}
