name: Lint & Test

on:
  push:
    branches: master
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Check Linting and Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.3.0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25.1'

      - name: Build Source
        run: go build -v ./...

      - name: Run Tests
        run: go test -v ./...
